spring:
  mongodb:
    host: localhost
    database: ${MONGO_DB:my_mongo_db}
    username: ${MONGO_USER:admin}
    password: ${MONGO_PASSWORD:admin}

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/${DB_NAME:my_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    mongodb:
      auto-index-creation: true

  jpa:
    hibernate:
      ddl-auto: none
    data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        password: ${REDIS_PASSWORD:}
  flyway:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/${DB_NAME:my_db}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    locations: "classpath:db/migration"
  ai:
    openai:
      api-key: ${OPEN_AI_KEY:NONE}
      base-url: ${OPEN_AI_URL:NONE}
      chat:
        options:
          model: ${OPEN_AI_MODEL:NONE}
          max-tokens: 2048



logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

jwt:
  private-key: classpath:/keys/private.pem
  public-key: classpath:/keys/public.pem

server:
  address: 0.0.0.0
  port: 8082
