spring:
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-oss-20b:free
          max-tokens: 2048


server:
  address: 0.0.0.0
  port: 8082
